import type {
  Application,
  ApplicationDocument,
  ApplicationEvent,
  ApplicationStatus,
  AuditEntry,
  Customer,
  Faq,
  Integration,
  Message,
  Service,
  Settings,
  Staff,
} from './types';

export const messages: Message[] = [];

export const customers: Customer[] = [
  {
    id: 'c_01',
    name: 'Ahmed Al-Mansoori',
    emiratesId: '784-1985-1234567-1',
    email: 'ahmed.m@example.ae',
    phone: '+971 50 111 2200',
    joinedAt: '2025-09-12',
    applications: 4,
  },
  {
    id: 'c_02',
    name: 'Fatima Khan',
    emiratesId: '784-1992-2345678-2',
    email: 'fatima.k@example.ae',
    phone: '+971 55 234 5670',
    joinedAt: '2025-11-03',
    applications: 2,
  },
  {
    id: 'c_03',
    name: 'Rajesh Pillai',
    emiratesId: '784-1980-3456789-3',
    email: 'rajesh.p@example.in',
    phone: '+971 56 345 6781',
    joinedAt: '2026-01-18',
    applications: 1,
  },
  {
    id: 'c_04',
    name: 'Maria Santos',
    emiratesId: '784-1991-4567890-4',
    email: 'maria.s@example.ph',
    phone: '+971 52 456 7892',
    joinedAt: '2026-02-22',
    applications: 3,
  },
  {
    id: 'c_05',
    name: 'Khalid Al-Suwaidi',
    emiratesId: '784-1975-5678901-5',
    email: 'k.suwaidi@example.ae',
    phone: '+971 50 567 8903',
    joinedAt: '2025-07-30',
    applications: 6,
  },
  {
    id: 'c_06',
    name: 'Sara Hussein',
    emiratesId: '784-1995-6789012-6',
    email: 'sara.h@example.eg',
    phone: '+971 54 678 9014',
    joinedAt: '2026-03-08',
    applications: 1,
  },
  {
    id: 'c_07',
    name: 'Mohammed Iqbal',
    emiratesId: '784-1988-7890123-7',
    email: 'm.iqbal@example.pk',
    phone: '+971 58 789 0125',
    joinedAt: '2025-12-19',
    applications: 2,
  },
  {
    id: 'c_08',
    name: 'Lina Botros',
    emiratesId: '784-1990-8901234-8',
    email: 'lina.b@example.lb',
    phone: '+971 50 890 1236',
    joinedAt: '2026-04-02',
    applications: 1,
  },
];

export const services: Service[] = [
  {
    id: 's_01',
    slug: 'employment-visa',
    category: 'immigration',
    titleEn: 'Employment visa',
    titleAr: 'تأشيرة عمل',
    authority: 'ICA',
    govFee: 1100,
    serviceFee: 250,
    processingDays: 7,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_02',
    slug: 'family-visa-spouse',
    category: 'immigration',
    titleEn: 'Family visa — spouse',
    titleAr: 'تأشيرة عائلية — زوج/ة',
    authority: 'GDRFA',
    govFee: 1320,
    serviceFee: 280,
    processingDays: 10,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_03',
    slug: 'emirates-id-renewal',
    category: 'immigration',
    titleEn: 'Emirates ID renewal',
    titleAr: 'تجديد الهوية الإماراتية',
    authority: 'ICA',
    govFee: 370,
    serviceFee: 90,
    processingDays: 5,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_04',
    slug: 'work-permit',
    category: 'labour',
    titleEn: 'Work permit',
    titleAr: 'تصريح عمل',
    authority: 'MOHRE',
    govFee: 750,
    serviceFee: 180,
    processingDays: 5,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_05',
    slug: 'labour-contract',
    category: 'labour',
    titleEn: 'Labour contract',
    titleAr: 'عقد عمل',
    authority: 'MOHRE',
    govFee: 200,
    serviceFee: 80,
    processingDays: 2,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_06',
    slug: 'trade-licence-renewal',
    category: 'company',
    titleEn: 'Trade licence renewal',
    titleAr: 'تجديد رخصة تجارية',
    authority: 'ADDED',
    govFee: 2400,
    serviceFee: 350,
    processingDays: 7,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_07',
    slug: 'driving-licence-renewal',
    category: 'transport',
    titleEn: 'Driving licence renewal',
    titleAr: 'تجديد رخصة قيادة',
    authority: 'ADP',
    govFee: 320,
    serviceFee: 100,
    processingDays: 1,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_08',
    slug: 'mulkiya-renewal',
    category: 'transport',
    titleEn: 'Mulkiya renewal',
    titleAr: 'تجديد ملكية السيارة',
    authority: 'ADP',
    govFee: 420,
    serviceFee: 120,
    processingDays: 1,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_09',
    slug: 'tawtheeq',
    category: 'realEstate',
    titleEn: 'Tawtheeq tenancy',
    titleAr: 'توثيق عقد الإيجار',
    authority: 'TAMM',
    govFee: 220,
    serviceFee: 110,
    processingDays: 3,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_10',
    slug: 'mofa-attestation',
    category: 'attestation',
    titleEn: 'MOFA attestation',
    titleAr: 'تصديق وزارة الخارجية',
    authority: 'MOFA',
    govFee: 150,
    serviceFee: 80,
    processingDays: 4,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_11',
    slug: 'medical-fitness',
    category: 'medical',
    titleEn: 'Medical fitness typing',
    titleAr: 'طباعة فحص اللياقة الطبية',
    authority: 'DOH',
    govFee: 270,
    serviceFee: 70,
    processingDays: 1,
    active: true,
    feesVisible: true,
  },
  {
    id: 's_12',
    slug: 'good-conduct',
    category: 'other',
    titleEn: 'Good-conduct certificate',
    titleAr: 'شهادة حسن سيرة وسلوك',
    authority: 'MOI',
    govFee: 100,
    serviceFee: 60,
    processingDays: 5,
    active: false,
    feesVisible: true,
  },
];

export const staff: Staff[] = [
  {
    id: 'u_01',
    name: 'Mariam Al-Hosani',
    email: 'mariam@synergytyping.com',
    role: 'admin',
    branch: 'Musaffah HQ',
    activeApplications: 0,
  },
  {
    id: 'u_02',
    name: 'Anil Verma',
    email: 'anil@synergytyping.com',
    role: 'staff',
    branch: 'Musaffah HQ',
    activeApplications: 5,
  },
  {
    id: 'u_03',
    name: 'Salma Hadid',
    email: 'salma@synergytyping.com',
    role: 'staff',
    branch: 'Musaffah HQ',
    activeApplications: 3,
  },
  {
    id: 'u_04',
    name: 'Joseph Daher',
    email: 'joseph@synergytyping.com',
    role: 'reviewer',
    branch: 'Musaffah HQ',
    activeApplications: 8,
  },
  {
    id: 'u_05',
    name: 'Hessa Al-Ali',
    email: 'hessa@synergytyping.com',
    role: 'staff',
    branch: 'Musaffah HQ',
    activeApplications: 2,
  },
  {
    id: 'u_06',
    name: 'Imran Sheikh',
    email: 'imran@synergytyping.com',
    role: 'reviewer',
    branch: 'Musaffah HQ',
    activeApplications: 4,
  },
];

export const faqs: Faq[] = [
  {
    id: 'f_01',
    category: 'Immigration',
    question: 'How long does an Employment visa take?',
    answer:
      'Typically 5–7 working days from submission to ICA approval, plus 1 day for Emirates ID stamping.',
    published: true,
  },
  {
    id: 'f_02',
    category: 'Immigration',
    question: 'Can I apply for a Family visa from outside the UAE?',
    answer: 'Yes — entry permit first, then status change after the family member arrives.',
    published: true,
  },
  {
    id: 'f_03',
    category: 'Immigration',
    question: 'When does my Emirates ID expire?',
    answer: 'Same day as your residence visa — they share an expiry date.',
    published: false,
  },
  {
    id: 'f_04',
    category: 'Labour (MOHRE)',
    question: 'Do I need Tawjeeh before I sign a labour contract?',
    answer: 'Yes for new workers under MOHRE — except for skill-level 1 and government employees.',
    published: true,
  },
  {
    id: 'f_05',
    category: 'Labour (MOHRE)',
    question: 'What is WPS and who must register?',
    answer:
      'Wage Protection System: every private-sector employer pays salaries through approved channels and reports to MOHRE.',
    published: true,
  },
  {
    id: 'f_06',
    category: 'Transport (ADP)',
    question: 'Can I renew my Mulkiya without a new insurance certificate?',
    answer: 'No — insurance valid for 13+ months from renewal date is required.',
    published: true,
  },
  {
    id: 'f_07',
    category: 'Transport (ADP)',
    question: 'How do I transfer plates between my own cars?',
    answer: 'Bring both Mulkiya, owner’s Emirates ID, and a passing inspection. Done same-day.',
    published: false,
  },
  {
    id: 'f_08',
    category: 'Real estate (TAMM)',
    question: 'Why is Tawtheeq required even for short tenancies?',
    answer:
      'It registers the tenancy with the Municipality and is the basis for utility activation and visa proof of address.',
    published: true,
  },
];

export const settings: Settings = {
  tradeName: 'Synergy Typing Services',
  phone: '+971 2 554 2220',
  whatsapp: '+971 50 660 1090',
  email: 'info@synergytyping.com',
  address: 'Shop #35, Al Maldieve Centre, Musaffah Industrial Area 10, Abu Dhabi, UAE',
  socialLinks: {
    facebook: '',
    instagram: '',
    twitter: '',
    linkedin: '',
    youtube: '',
    tiktok: '',
    snapchat: '',
    whatsappChannel: '',
  },
  licence: '',
  trn: '',
};

export const integrations: Integration[] = [
  { name: 'Stripe', status: 'not_connected' },
  { name: 'Telr', status: 'not_connected' },
  { name: 'Network International', status: 'not_connected' },
  { name: 'Resend (email)', status: 'sandbox' },
  { name: 'WhatsApp Business', status: 'planned' },
  { name: 'Cloudflare R2 (docs)', status: 'sandbox' },
  { name: 'Inngest (jobs)', status: 'not_connected' },
  { name: 'PostHog', status: 'not_connected' },
  { name: 'Sentry', status: 'not_connected' },
];

const mkApp = (
  id: number,
  customerId: string,
  serviceId: string,
  status: ApplicationStatus,
  assignedTo: string | undefined,
  submittedAt: string,
  updatedAt: string,
  documents: ApplicationDocument[],
  events: ApplicationEvent[],
): Application => {
  const svc = services.find((s) => s.id === serviceId)!;
  const govFee = svc.govFee;
  const serviceFee = svc.serviceFee;
  const vat = Math.round((govFee + serviceFee) * 0.05);
  return {
    id: `a_${String(id).padStart(2, '0')}`,
    reference: `STS-2026-${String(1000 + id)}`,
    customerId,
    serviceId,
    status,
    assignedTo,
    submittedAt,
    updatedAt,
    govFee,
    serviceFee,
    vat,
    total: govFee + serviceFee + vat,
    documents,
    events,
  };
};

export const applications: Application[] = [
  mkApp(
    1,
    'c_01',
    's_01',
    'with_government',
    'u_02',
    '2026-04-22T08:14:00Z',
    '2026-04-24T11:32:00Z',
    [
      { name: 'Passport.pdf', status: 'verified', uploadedAt: '2026-04-22T08:15:00Z' },
      { name: 'Photo.jpg', status: 'verified', uploadedAt: '2026-04-22T08:16:00Z' },
      { name: 'Offer letter.pdf', status: 'verified', uploadedAt: '2026-04-22T08:17:00Z' },
    ],
    [
      { at: '2026-04-22T08:14:00Z', actor: 'Ahmed Al-Mansoori', action: 'Submitted application' },
      { at: '2026-04-22T09:02:00Z', actor: 'Anil Verma', action: 'Started review' },
      { at: '2026-04-23T14:20:00Z', actor: 'Anil Verma', action: 'Verified all documents' },
      {
        at: '2026-04-24T11:32:00Z',
        actor: 'system',
        action: 'Transitioned to with_government',
        note: 'Submitted to ICA portal',
      },
    ],
  ),
  mkApp(
    2,
    'c_02',
    's_03',
    'missing_docs',
    'u_03',
    '2026-04-23T10:00:00Z',
    '2026-04-24T15:10:00Z',
    [
      { name: 'Old Emirates ID.jpg', status: 'verified', uploadedAt: '2026-04-23T10:01:00Z' },
      { name: 'Photo.jpg', status: 'rejected', uploadedAt: '2026-04-23T10:02:00Z' },
    ],
    [
      { at: '2026-04-23T10:00:00Z', actor: 'Fatima Khan', action: 'Submitted application' },
      {
        at: '2026-04-24T15:10:00Z',
        actor: 'Salma Hadid',
        action: 'Marked photo as rejected',
        note: 'Background not white',
      },
    ],
  ),
  mkApp(
    3,
    'c_03',
    's_07',
    'approved',
    'u_05',
    '2026-04-21T07:30:00Z',
    '2026-04-22T12:00:00Z',
    [
      { name: 'Eye test.pdf', status: 'verified', uploadedAt: '2026-04-21T07:31:00Z' },
      { name: 'Old DL.pdf', status: 'verified', uploadedAt: '2026-04-21T07:32:00Z' },
    ],
    [
      { at: '2026-04-21T07:30:00Z', actor: 'Rajesh Pillai', action: 'Submitted application' },
      { at: '2026-04-22T12:00:00Z', actor: 'system', action: 'Transitioned to approved' },
    ],
  ),
  mkApp(
    4,
    'c_04',
    's_04',
    'under_review',
    'u_04',
    '2026-04-24T06:45:00Z',
    '2026-04-24T09:15:00Z',
    [
      { name: 'Passport.pdf', status: 'verified', uploadedAt: '2026-04-24T06:46:00Z' },
      { name: 'Visa copy.pdf', status: 'pending', uploadedAt: '2026-04-24T06:47:00Z' },
      { name: 'Tawjeeh certificate.pdf', status: 'pending', uploadedAt: '2026-04-24T06:48:00Z' },
    ],
    [
      { at: '2026-04-24T06:45:00Z', actor: 'Maria Santos', action: 'Submitted application' },
      { at: '2026-04-24T09:15:00Z', actor: 'Joseph Daher', action: 'Started review' },
    ],
  ),
  mkApp(
    5,
    'c_05',
    's_06',
    'submitted',
    undefined,
    '2026-04-25T05:10:00Z',
    '2026-04-25T05:10:00Z',
    [
      {
        name: 'Trade licence (current).pdf',
        status: 'pending',
        uploadedAt: '2026-04-25T05:11:00Z',
      },
      { name: 'MOA.pdf', status: 'pending', uploadedAt: '2026-04-25T05:12:00Z' },
    ],
    [{ at: '2026-04-25T05:10:00Z', actor: 'Khalid Al-Suwaidi', action: 'Submitted application' }],
  ),
  mkApp(
    6,
    'c_06',
    's_02',
    'draft',
    undefined,
    '2026-04-25T04:30:00Z',
    '2026-04-25T04:30:00Z',
    [],
    [{ at: '2026-04-25T04:30:00Z', actor: 'Sara Hussein', action: 'Created draft' }],
  ),
  mkApp(
    7,
    'c_07',
    's_05',
    'closed',
    'u_02',
    '2026-04-15T11:20:00Z',
    '2026-04-19T16:00:00Z',
    [{ name: 'Old contract.pdf', status: 'verified', uploadedAt: '2026-04-15T11:21:00Z' }],
    [
      { at: '2026-04-15T11:20:00Z', actor: 'Mohammed Iqbal', action: 'Submitted application' },
      {
        at: '2026-04-19T16:00:00Z',
        actor: 'Anil Verma',
        action: 'Closed',
        note: 'Customer collected documents',
      },
    ],
  ),
  mkApp(
    8,
    'c_08',
    's_09',
    'rejected',
    'u_06',
    '2026-04-20T13:45:00Z',
    '2026-04-21T09:30:00Z',
    [{ name: 'Tenancy contract.pdf', status: 'rejected', uploadedAt: '2026-04-20T13:46:00Z' }],
    [
      { at: '2026-04-20T13:45:00Z', actor: 'Lina Botros', action: 'Submitted application' },
      {
        at: '2026-04-21T09:30:00Z',
        actor: 'Imran Sheikh',
        action: 'Rejected',
        note: 'Landlord signature missing',
      },
    ],
  ),
  mkApp(
    9,
    'c_01',
    's_10',
    'with_government',
    'u_06',
    '2026-04-23T16:00:00Z',
    '2026-04-24T08:00:00Z',
    [{ name: 'Degree certificate.pdf', status: 'verified', uploadedAt: '2026-04-23T16:01:00Z' }],
    [
      { at: '2026-04-23T16:00:00Z', actor: 'Ahmed Al-Mansoori', action: 'Submitted application' },
      { at: '2026-04-24T08:00:00Z', actor: 'Imran Sheikh', action: 'Sent to MOFA portal' },
    ],
  ),
  mkApp(
    10,
    'c_05',
    's_08',
    'approved',
    'u_03',
    '2026-04-22T07:00:00Z',
    '2026-04-23T10:30:00Z',
    [
      { name: 'Insurance.pdf', status: 'verified', uploadedAt: '2026-04-22T07:01:00Z' },
      { name: 'Old Mulkiya.pdf', status: 'verified', uploadedAt: '2026-04-22T07:02:00Z' },
    ],
    [
      { at: '2026-04-22T07:00:00Z', actor: 'Khalid Al-Suwaidi', action: 'Submitted application' },
      { at: '2026-04-23T10:30:00Z', actor: 'system', action: 'Transitioned to approved' },
    ],
  ),
  mkApp(
    11,
    'c_05',
    's_11',
    'submitted',
    undefined,
    '2026-04-25T03:15:00Z',
    '2026-04-25T03:15:00Z',
    [{ name: 'Visa copy.pdf', status: 'pending', uploadedAt: '2026-04-25T03:16:00Z' }],
    [{ at: '2026-04-25T03:15:00Z', actor: 'Khalid Al-Suwaidi', action: 'Submitted application' }],
  ),
  mkApp(
    12,
    'c_04',
    's_09',
    'under_review',
    'u_04',
    '2026-04-24T14:00:00Z',
    '2026-04-25T07:00:00Z',
    [
      { name: 'Tenancy contract.pdf', status: 'verified', uploadedAt: '2026-04-24T14:01:00Z' },
      { name: 'Title deed.pdf', status: 'pending', uploadedAt: '2026-04-24T14:02:00Z' },
    ],
    [
      { at: '2026-04-24T14:00:00Z', actor: 'Maria Santos', action: 'Submitted application' },
      { at: '2026-04-25T07:00:00Z', actor: 'Joseph Daher', action: 'Started review' },
    ],
  ),
];

export const auditLog: AuditEntry[] = [
  {
    id: 'al_01',
    at: '2026-04-25T07:00:00Z',
    actor: 'Joseph Daher',
    action: 'application.review_started',
    target: 'STS-2026-1012',
    meta: 'Mulkiya · Maria Santos',
  },
  {
    id: 'al_02',
    at: '2026-04-25T05:10:00Z',
    actor: 'Khalid Al-Suwaidi',
    action: 'application.submitted',
    target: 'STS-2026-1005',
    meta: 'Trade licence renewal',
  },
  {
    id: 'al_03',
    at: '2026-04-25T04:30:00Z',
    actor: 'Sara Hussein',
    action: 'application.draft_created',
    target: 'STS-2026-1006',
    meta: 'Family visa',
  },
  {
    id: 'al_04',
    at: '2026-04-25T03:15:00Z',
    actor: 'Khalid Al-Suwaidi',
    action: 'application.submitted',
    target: 'STS-2026-1011',
    meta: 'Medical fitness',
  },
  {
    id: 'al_05',
    at: '2026-04-24T15:10:00Z',
    actor: 'Salma Hadid',
    action: 'document.rejected',
    target: 'STS-2026-1002',
    meta: 'Photo.jpg — background not white',
  },
  {
    id: 'al_06',
    at: '2026-04-24T11:32:00Z',
    actor: 'system',
    action: 'application.transitioned',
    target: 'STS-2026-1001',
    meta: 'with_government',
  },
  {
    id: 'al_07',
    at: '2026-04-24T09:15:00Z',
    actor: 'Joseph Daher',
    action: 'application.review_started',
    target: 'STS-2026-1004',
    meta: 'Work permit',
  },
  {
    id: 'al_08',
    at: '2026-04-24T08:00:00Z',
    actor: 'Imran Sheikh',
    action: 'application.sent_to_authority',
    target: 'STS-2026-1009',
    meta: 'MOFA portal',
  },
  {
    id: 'al_09',
    at: '2026-04-23T16:00:00Z',
    actor: 'Ahmed Al-Mansoori',
    action: 'application.submitted',
    target: 'STS-2026-1009',
    meta: 'MOFA attestation',
  },
  {
    id: 'al_10',
    at: '2026-04-23T14:20:00Z',
    actor: 'Anil Verma',
    action: 'document.verified_all',
    target: 'STS-2026-1001',
    meta: 'Employment visa',
  },
];
